### PR TITLE
Clean up boardTest example and add headers to other examples

### PR DESCRIPTION
**Pull request by cleveHEX**
- [x] Ready for merge

### CODE REVIEW

**Review by JarekParal — COMMENTED** [review]
Did you test this program? I'm not sure if the if on line 28 work correctly.

**Review by JarekParal — COMMENTED** [review]
I suggest to change the name of example "leds" to something as "testAllLeds" or anything similar?

**Comment by cleveHEX** [comment]
@JarekParal 
I think it should not contain test, ledsExample maybie?

**Comment by JarekParal** [comment]
@CornyjK 
But the main folder has name `examples`.

**Comment by cleveHEX** [comment]
@JarekParal 
Then your name is probably the best one. This would be the latest change to this PR.

**Pull request merged**
